#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TrustVisionAPI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif



@class TSApiError;
@class TVAPIClientSettingsResponse;
@class UIImage;
@class TVCardInfoRequest;
@class TVAPICardInfoResponse;
@class TVAPICompareFacesResponse;
@class TVAPIVerifyLivenessResponse;
@class TVAPIVerifyIdCardSanityResponse;
@class TVAPIVerifyPortraitSanityResponse;
@class TVRequestImage;
@class TVCardInfoSyncRequest;

SWIFT_CLASS("_TtC14TrustVisionAPI11TSAPIClient")
@interface TSAPIClient : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) TSAPIClient * _Nonnull shared;)
+ (TSAPIClient * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)authorizeWithGetAuthorization:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSString * _Nullable, SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable)))getAuthorization;
- (void)getClientSettingsWithCompletion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIClientSettingsResponse * _Nullable))completion;
- (void)uploadImageWithImage:(UIImage * _Nonnull)image label:(NSString * _Nullable)label metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)readIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkReadIdCardInfoWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICardInfoResponse * _Nullable))completion;
- (void)compareFacesWithImage1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nonnull)image2Id completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkCompareFacesWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICompareFacesResponse * _Nullable))completion;
- (void)verifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures imageIds:(NSArray<NSString *> * _Nonnull)imageIds completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkVerifyLivenessWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyLivenessResponse * _Nullable))completion;
- (void)verifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nullable)image2Id completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkVerifyIdCardSanityWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyIdCardSanityResponse * _Nullable))completion;
- (void)verifyPortraitSanityWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkVerifyPortraitSanityWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyPortraitSanityResponse * _Nullable))completion;
- (void)pollVerifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nullable)image2Id completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyIdCardSanityResponse * _Nullable))completion;
- (void)pollCompareFacesWithImage1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nonnull)image2Id completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICompareFacesResponse * _Nullable))completion;
- (void)pollReadIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICardInfoResponse * _Nullable))completion;
- (void)pollVerifyPortraitSanityWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyPortraitSanityResponse * _Nullable))completion;
- (void)pollVerifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures imageIds:(NSArray<NSString *> * _Nonnull)imageIds completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyLivenessResponse * _Nullable))completion;
- (void)syncCompareFacesWithImage1:(TVRequestImage * _Nonnull)image1 image2:(TVRequestImage * _Nonnull)image2 completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICompareFacesResponse * _Nullable))completion;
- (void)syncReadIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoSyncRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICardInfoResponse * _Nullable))completion;
- (void)syncVerifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1:(TVRequestImage * _Nonnull)image1 image2:(TVRequestImage * _Nullable)image2 completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyIdCardSanityResponse * _Nullable))completion;
- (void)syncVerifyPortraitSanityWithImage:(TVRequestImage * _Nonnull)image completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyPortraitSanityResponse * _Nullable))completion;
- (void)syncVerifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures images:(NSArray<TVRequestImage *> * _Nonnull)images completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyLivenessResponse * _Nullable))completion;
@end



@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface TSAPIClient (SWIFT_EXTENSION(TrustVisionAPI)) <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
@end








SWIFT_CLASS("_TtC14TrustVisionAPI10TSApiError")
@interface TSApiError : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI9TVAPIBase")
@interface TVAPIBase : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVAPICameraOption, closed) {
  TVAPICameraOptionFront = 0,
  TVAPICameraOptionBack = 1,
};


SWIFT_CLASS("_TtC14TrustVisionAPI21TVAPICardInfoResponse")
@interface TVAPICardInfoResponse : TVAPIBase
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI21TVAPICardInfoResponse9CardImage")
@interface CardImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI21TVAPICardInfoResponse3Ocr")
@interface Ocr : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI21TVAPICardInfoResponse4Info")
@interface Info : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI27TVAPIClientSettingsResponse")
@interface TVAPIClientSettingsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Orientation, closed) {
  OrientationHorizontal = 0,
  OrientationVertical = 1,
};


SWIFT_CLASS("_TtCC14TrustVisionAPI27TVAPIClientSettingsResponse8Settings")
@interface Settings : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI27TVAPIClientSettingsResponse8CardType")
@interface CardType : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI25TVAPICompareFacesResponse")
@interface TVAPICompareFacesResponse : TVAPIBase
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI25TVAPICompareFacesResponse11CompareFace")
@interface CompareFace : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TSCompareFaceResult, closed) {
  TSCompareFaceResultMatched = 0,
  TSCompareFaceResultUnmatched = 1,
  TSCompareFaceResultUnsure = 2,
};


SWIFT_CLASS("_TtCC14TrustVisionAPI25TVAPICompareFacesResponse5Image")
@interface Image : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI25TVAPICompareFacesResponse4Face")
@interface Face : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI25TVAPICompareFacesResponse11BoundingBox")
@interface BoundingBox : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI18TVAPIImageResponse")
@interface TVAPIImageResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI18TVAPIImageResponse7CardBox")
@interface CardBox : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVAPILivenessOption, closed) {
  TVAPILivenessOptionActive = 0,
  TVAPILivenessOptionPassive = 1,
};


SWIFT_CLASS("_TtC14TrustVisionAPI10TVAPIPoint")
@interface TVAPIPoint : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI7TVAPIQR")
@interface TVAPIQR : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVAPIQRType, closed) {
  TVAPIQRTypeQrCode = 0,
  TVAPIQRTypeBarCode = 1,
};

typedef SWIFT_ENUM(NSInteger, TVAPIResult, closed) {
  TVAPIResultSuccess = 0,
  TVAPIResultFailure = 1,
};


SWIFT_CLASS("_TtC14TrustVisionAPI11TVAPISanity")
@interface TVAPISanity : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVAPIScanQrMode, closed) {
  TVAPIScanQrModeNone = 0,
  TVAPIScanQrModeSeparateStep = 1,
  TVAPIScanQrModeWithCard = 2,
};


SWIFT_CLASS("_TtC14TrustVisionAPI31TVAPIVerifyIdCardSanityResponse")
@interface TVAPIVerifyIdCardSanityResponse : TVAPIBase
@end


SWIFT_CLASS("_TtC14TrustVisionAPI27TVAPIVerifyLivenessResponse")
@interface TVAPIVerifyLivenessResponse : TVAPIBase
@end


SWIFT_CLASS("_TtC14TrustVisionAPI33TVAPIVerifyPortraitSanityResponse")
@interface TVAPIVerifyPortraitSanityResponse : TVAPIBase
@end


SWIFT_CLASS("_TtC14TrustVisionAPI17TVCardInfoRequest")
@interface TVCardInfoRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI21TVCardInfoSyncRequest")
@interface TVCardInfoSyncRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI14TVRequestImage")
@interface TVRequestImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TrustVisionAPI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif



@class TSApiError;
@class TVAPIClientSettingsResponse;
@class UIImage;
@class TVCardInfoRequest;
@class TVAPICardInfoResponse;
@class TVAPICompareFacesResponse;
@class TVAPIVerifyLivenessResponse;
@class TVAPIVerifyIdCardSanityResponse;
@class TVAPIVerifyPortraitSanityResponse;
@class TVRequestImage;
@class TVCardInfoSyncRequest;

SWIFT_CLASS("_TtC14TrustVisionAPI11TSAPIClient")
@interface TSAPIClient : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) TSAPIClient * _Nonnull shared;)
+ (TSAPIClient * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)authorizeWithGetAuthorization:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSString * _Nullable, SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable)))getAuthorization;
- (void)getClientSettingsWithCompletion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIClientSettingsResponse * _Nullable))completion;
- (void)uploadImageWithImage:(UIImage * _Nonnull)image label:(NSString * _Nullable)label metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)readIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkReadIdCardInfoWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICardInfoResponse * _Nullable))completion;
- (void)compareFacesWithImage1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nonnull)image2Id completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkCompareFacesWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICompareFacesResponse * _Nullable))completion;
- (void)verifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures imageIds:(NSArray<NSString *> * _Nonnull)imageIds completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkVerifyLivenessWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyLivenessResponse * _Nullable))completion;
- (void)verifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nullable)image2Id completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkVerifyIdCardSanityWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyIdCardSanityResponse * _Nullable))completion;
- (void)verifyPortraitSanityWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, NSString * _Nullable))completion;
- (void)checkVerifyPortraitSanityWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyPortraitSanityResponse * _Nullable))completion;
- (void)pollVerifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nullable)image2Id completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyIdCardSanityResponse * _Nullable))completion;
- (void)pollCompareFacesWithImage1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nonnull)image2Id completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICompareFacesResponse * _Nullable))completion;
- (void)pollReadIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICardInfoResponse * _Nullable))completion;
- (void)pollVerifyPortraitSanityWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyPortraitSanityResponse * _Nullable))completion;
- (void)pollVerifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures imageIds:(NSArray<NSString *> * _Nonnull)imageIds completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyLivenessResponse * _Nullable))completion;
- (void)syncCompareFacesWithImage1:(TVRequestImage * _Nonnull)image1 image2:(TVRequestImage * _Nonnull)image2 completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICompareFacesResponse * _Nullable))completion;
- (void)syncReadIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoSyncRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPICardInfoResponse * _Nullable))completion;
- (void)syncVerifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1:(TVRequestImage * _Nonnull)image1 image2:(TVRequestImage * _Nullable)image2 completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyIdCardSanityResponse * _Nullable))completion;
- (void)syncVerifyPortraitSanityWithImage:(TVRequestImage * _Nonnull)image completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyPortraitSanityResponse * _Nullable))completion;
- (void)syncVerifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures images:(NSArray<TVRequestImage *> * _Nonnull)images completion:(void (^ _Nonnull)(NSArray<TSApiError *> * _Nonnull, TVAPIVerifyLivenessResponse * _Nullable))completion;
@end



@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface TSAPIClient (SWIFT_EXTENSION(TrustVisionAPI)) <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
@end








SWIFT_CLASS("_TtC14TrustVisionAPI10TSApiError")
@interface TSApiError : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI9TVAPIBase")
@interface TVAPIBase : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVAPICameraOption, closed) {
  TVAPICameraOptionFront = 0,
  TVAPICameraOptionBack = 1,
};


SWIFT_CLASS("_TtC14TrustVisionAPI21TVAPICardInfoResponse")
@interface TVAPICardInfoResponse : TVAPIBase
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI21TVAPICardInfoResponse9CardImage")
@interface CardImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI21TVAPICardInfoResponse3Ocr")
@interface Ocr : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI21TVAPICardInfoResponse4Info")
@interface Info : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI27TVAPIClientSettingsResponse")
@interface TVAPIClientSettingsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Orientation, closed) {
  OrientationHorizontal = 0,
  OrientationVertical = 1,
};


SWIFT_CLASS("_TtCC14TrustVisionAPI27TVAPIClientSettingsResponse8Settings")
@interface Settings : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI27TVAPIClientSettingsResponse8CardType")
@interface CardType : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI25TVAPICompareFacesResponse")
@interface TVAPICompareFacesResponse : TVAPIBase
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI25TVAPICompareFacesResponse11CompareFace")
@interface CompareFace : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TSCompareFaceResult, closed) {
  TSCompareFaceResultMatched = 0,
  TSCompareFaceResultUnmatched = 1,
  TSCompareFaceResultUnsure = 2,
};


SWIFT_CLASS("_TtCC14TrustVisionAPI25TVAPICompareFacesResponse5Image")
@interface Image : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI25TVAPICompareFacesResponse4Face")
@interface Face : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI25TVAPICompareFacesResponse11BoundingBox")
@interface BoundingBox : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI18TVAPIImageResponse")
@interface TVAPIImageResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI18TVAPIImageResponse7CardBox")
@interface CardBox : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVAPILivenessOption, closed) {
  TVAPILivenessOptionActive = 0,
  TVAPILivenessOptionPassive = 1,
};


SWIFT_CLASS("_TtC14TrustVisionAPI10TVAPIPoint")
@interface TVAPIPoint : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI7TVAPIQR")
@interface TVAPIQR : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVAPIQRType, closed) {
  TVAPIQRTypeQrCode = 0,
  TVAPIQRTypeBarCode = 1,
};

typedef SWIFT_ENUM(NSInteger, TVAPIResult, closed) {
  TVAPIResultSuccess = 0,
  TVAPIResultFailure = 1,
};


SWIFT_CLASS("_TtC14TrustVisionAPI11TVAPISanity")
@interface TVAPISanity : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVAPIScanQrMode, closed) {
  TVAPIScanQrModeNone = 0,
  TVAPIScanQrModeSeparateStep = 1,
  TVAPIScanQrModeWithCard = 2,
};


SWIFT_CLASS("_TtC14TrustVisionAPI31TVAPIVerifyIdCardSanityResponse")
@interface TVAPIVerifyIdCardSanityResponse : TVAPIBase
@end


SWIFT_CLASS("_TtC14TrustVisionAPI27TVAPIVerifyLivenessResponse")
@interface TVAPIVerifyLivenessResponse : TVAPIBase
@end


SWIFT_CLASS("_TtC14TrustVisionAPI33TVAPIVerifyPortraitSanityResponse")
@interface TVAPIVerifyPortraitSanityResponse : TVAPIBase
@end


SWIFT_CLASS("_TtC14TrustVisionAPI17TVCardInfoRequest")
@interface TVCardInfoRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI21TVCardInfoSyncRequest")
@interface TVCardInfoSyncRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI14TVRequestImage")
@interface TVRequestImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
